services:
  mysql:
    image: mysql:8.0
    container_name: innovatech-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: innovatech
    ports:
      - "3306:3306"
    volumes:
      - innovatech_mysql_data:/var/lib/mysql

  ventas-backend:
    build:
      context: ./back-Ventas_SpringBoot/Springboot-API-REST
    container_name: innovatech-ventas-backend
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/innovatech
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  despachos-backend:
    build:
      context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
    container_name: innovatech-despachos-backend
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/innovatech
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    ports:
      - "8081:8081"
    depends_on:
      - mysql

volumes:
  innovatech_mysql_data: